from .extra_serializers import TypeProductSimpleSerializer, EppEstructuralForestalSerializer, \
    HerramientaAccesorioSerializer
from .type_product_viewset import TypeProductSerializer, TypeProductViewSet
from .epp_estructural_viewset import EppEstructuralSerializer, EppEstructuralViewSet
