# Generated by Django 4.2.1 on 2023-08-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank='', default='otros/subir.png', upload_to='otros/')),
                ('codigo', models.CharField(blank=True, max_length=150, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otros', to='inventory.typeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Epp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank='', default='epp/subir.png', upload_to='epp/')),
                ('codigo', models.CharField(blank=True, max_length=150, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('marca', models.CharField(blank=True, max_length=150)),
                ('industria', models.CharField(blank=True, max_length=150)),
                ('talla', models.CharField(blank=True, max_length=150)),
                ('año_fabricacion', models.CharField(blank=True, max_length=150)),
                ('color', models.CharField(blank=True, max_length=150)),
                ('color_reflectivo', models.CharField(blank=True, max_length=150)),
                ('certificacion', models.CharField(blank=True, max_length=150)),
                ('color_suspensores', models.CharField(blank=True, max_length=150)),
                ('material', models.CharField(blank=True, max_length=150)),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epp', to='inventory.typeproduct')),
            ],
        ),
    ]
