# Generated by Django 4.2.1 on 2023-06-28 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HerramientasAccesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank='', default='herramientas_accesorios/subir.png', upload_to='herramientas_accesorios/')),
                ('codigo', models.CharField(blank=True, max_length=150, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('marca', models.CharField(blank=True, max_length=150)),
                ('industria', models.CharField(blank=True, max_length=150)),
                ('color', models.CharField(blank=True, max_length=150)),
                ('certificacion', models.CharField(blank=True, max_length=150)),
                ('material', models.CharField(blank=True, max_length=150)),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_accesorios', to='inventory.typeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='EppEstructuralForestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank='', default='epp_estructural_forestal/subir.png', upload_to='epp_estructural_forestal/')),
                ('codigo', models.CharField(blank=True, max_length=150, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('marca', models.CharField(blank=True, max_length=150)),
                ('industria', models.CharField(blank=True, max_length=150)),
                ('talla', models.CharField(blank=True, max_length=150)),
                ('año_fabricacion', models.CharField(blank=True, max_length=150)),
                ('color', models.CharField(blank=True, max_length=150)),
                ('color_reflectivo', models.CharField(blank=True, max_length=150)),
                ('certificacion', models.CharField(blank=True, max_length=150)),
                ('color_suspensores', models.CharField(blank=True, max_length=150)),
                ('material', models.CharField(blank=True, max_length=150)),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epp_estructural_forestal', to='inventory.typeproduct')),
            ],
        ),
    ]
