# Generated by Django 4.2.1 on 2023-08-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomberouser',
            old_name='type',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='bomberouser',
            name='blood_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='bomberouser',
            name='password',
            field=models.CharField(blank=True, default='bomberosuubr', max_length=128, null=True, verbose_name='password'),
        ),
    ]
