# Generated by Django 4.2.1 on 2023-08-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_type_bomberouser_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomberouser',
            old_name='position',
            new_name='type',
        ),
    ]
