# Generated by Django 4.2.1 on 2023-08-03 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_position_bomberouser_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomberouser',
            old_name='type',
            new_name='position',
        ),
    ]
