# Generated by Django 4.2.1 on 2023-08-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_type_bomberouser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomberouser',
            name='type',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
