# Generated by Django 4.2.1 on 2023-08-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_bomberouser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomberouser',
            name='type',
        ),
    ]
