# Generated by Django 4.2.1 on 2023-08-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_bomberouser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomberouser',
            name='other',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
