# Generated by Django 4.2.1 on 2023-08-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_bomberouser_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomberouser',
            name='other',
        ),
    ]
